### ISSUE TITLE
Suspicious values in MPI_Testany records 

### ISSUE THREAD

**Issue by dchapp** [sstsimulator/sst-dumpi#19]
Hello,

I am using libdumpi to trace executions of the Graph500 BFS benchmark (specifically, the reference implementation available at: https://github.com/Graph500/graph500), and I have noticed that in records of MPI_Testany calls, there are some suspicious values for index and for the bytes field in the status. I have included below two examples that show both instances of the suspicious values.

Example 1:

    MPI_Testany entering at walltime 56247.501448930, cputime 1.374186170 seconds in thread 0.
    int count=4                                                                    
    MPI_Request requests[4]=[6, 7, 8, 9]                                           
    **int index=-32766**                                                               
    int flag=0                                                                     
    MPI_Status status=<IGNORED>                                                    
    MPI_Testany returning at walltime 56247.501454870, cputime 1.374192287 seconds in thread 0.

Example 2:

    MPI_Testany entering at walltime 56247.502554376, cputime 1.375274547 seconds in thread 0.
    int count=4                                                                    
    MPI_Request requests[4]=[10, 11, 12, 13]                                       
    int index=0                                                                    
    int flag=1                                                                     
    MPI_Status status=[{**bytes=-32766**, cancelled=0, source=0, tag=2048, error=0}]   
    MPI_Testany returning at walltime 56247.502558329, cputime 1.375278986 seconds in thread 0.

Since the suspicious value in both cases is -32766, I suspect an overflow issue, but I am not sufficiently familiar with MPI, libdumpi, and the benchmark I'm tracing to completely rule out other causes. Can someone confirm whether this is actually a bug? Thanks.

**Comment by jjwilke** [comment]
Which MPI and version is this?

Neither case is necessarily an error. MPICH defines MPI_UNDEFINED to be -32766. In the first case, your flag is 0 so index is undefined since nothing is done.
In the second case, I’m not sure why (maybe you are using custom MPI types) the bytes is sent back as undefined.
This behavior comes from the underlying MPI, not DUMPI.

This should probably be enhanced so that it prints MPI_UNDEFINED instead of the integer.

-Jeremy

**Comment by dchapp** [comment]
I am using MVAPICH 2.2. Thank you for explaining why I should expect to see an undefined index in the first case, and for explaining how MPICH defines MPI_UNDEFINED. Since this isn't an issue with DUMPI, should I close this issue?
