### ISSUE TITLE
Issue while building sst-dumpi

### ISSUE THREAD

**Issue by hkhetawat** [sstsimulator/sst-dumpi#5]
I am trying to build sst-dumpi from source with the following configuration line:
../configure --enable-libdumpi --enable-libundumpi --prefix=/home/harsh/sst-dumpi/install CC=mpicc CXX=mpicxx

This is on a ubuntu system. I have also tried this on a OS X machine. I get the following error when I make:
../../../dumpi/libdumpi/mpibindings2.c: At top level:
../../../dumpi/libdumpi/mpibindings2.c:187:5: error: conflicting types for ‘MPI_Send’
 int MPI_Send(DUMPI_CONST void *buf, int count, MPI_Datatype datatype, int dest,
     ^
In file included from ../../../dumpi/libdumpi/data.h:48:0,
                 from ../../../dumpi/libdumpi/mpibindings-maps.h:50,
                 from ../../../dumpi/libdumpi/mpibindings.h:48,
                 from ../../../dumpi/libdumpi/mpibindings2.c:46:
/usr/lib/openmpi/include/mpi.h:1679:20: note: previous declaration of ‘MPI_Send’ was here
 OMPI_DECLSPEC  int MPI_Send(const void *buf, int count, MPI_Datatype datatype, 
                    ^
../../../dumpi/libdumpi/mpibindings2.c:255:5: error: conflicting types for ‘MPI_Get_count’
 int MPI_Get_count(DUMPI_CONST MPI_Status *status, MPI_Datatype datatype, int *c
     ^
In file included from ../../../dumpi/libdumpi/data.h:48:0,
                 from ../../../dumpi/libdumpi/mpibindings-maps.h:50,
                 from ../../../dumpi/libdumpi/mpibindings.h:48,
                 from ../../../dumpi/libdumpi/mpibindings2.c:46:
/usr/lib/openmpi/include/mpi.h:1455:20: note: previous declaration of ‘MPI_Get_count’ was here
 OMPI_DECLSPEC  int MPI_Get_count(const MPI_Status *status, MPI_Datatype datatyp
                    ^
../../../dumpi/libdumpi/mpibindings2.c:287:5: error: conflicting types for ‘MPI_Bsend’
 int MPI_Bsend(DUMPI_CONST void *buf, int count, MPI_Datatype datatype, int dest
     ^
In file included from ../../../dumpi/libdumpi/data.h:48:0,
                 from ../../../dumpi/libdumpi/mpibindings-maps.h:50,
                 from ../../../dumpi/libdumpi/mpibindings.h:48,
                 from ../../../dumpi/libdumpi/mpibindings2.c:46:
/usr/lib/openmpi/include/mpi.h:1235:20: note: previous declaration of ‘MPI_Bsend’ was here

And so on...

**Comment by Chevalier-Maxime** [comment]
Add CFLAGS="-DMPICH_SUPPRESS_PROTOTYPES=1 -DHAVE_PRAGMA_HP_SEC_DEF=1" to configure or you can try with new release
