### ISSUE TITLE
Install DUMPI libaray

### ISSUE THREAD

**Issue by jw447** [sstsimulator/sst-dumpi#7]
Hi,

I am trying to install dumpi library when I encountered the problem. When I cloned the git and was tryign to run `./bootstrap.sh`, the terminal prompted an error saying 

> ./bootstrap.sh: 14: ./bootstrap.sh: glibtoolize: not found
> ./bootstrap.sh: 15: ./bootstrap.sh: autoreconf: not found

I am wondering how did it happen and how to solve it.

Thanks,

**Comment by jjwilke** [comment]
You do not have autoconf installed or libtool installed on your system. You can build from the tarball - but you will at least need automake for this.
These are common packages and should be easy to install with whatever package manger you have on your system.

1) autoconf
2) automake
3) libtool

-Jeremy

**Comment by jw447** [comment]
Thank you Jeremy, I didn’t realize that glibtoolize and autoreconf are packages that I should install. May I follow up another question that is: after I run ./bootstrap.sh to install dumpi library, where should I add -L$(PATH_TO_DUMPI) -ldumpi to link dumpi library to mpi calls?

Thanks,
Jinzhen

**Comment by jjwilke** [comment]
That will depend on your build system. The -ldumpi goes in LIBS and -L... goes in LDFLAGS for Makefiles. CMake is a little different.

-Jeremy

**Comment by jw447** [comment]
Thanks, so for my makefiles, should I change it update like this? I am not getting new dumpi log file though.

Jinzhen

**Comment by jjwilke** [comment]
Can you send a plain text cut/paste? My virus blocker won't let the picture through.

-Jeremy

**Comment by jw447** [comment]
I am forwarding my c code and make file as attachments. Thank you for your time.

Thanks,
Jinzhen

**Comment by jw447** [comment]
Make file:

EXECS=mpi_hello_world
MPICC?=mpicc
LDFLAGS=-L$(/home/jon/sst-dumpi)
LIBS=-ldumpi
all: ${EXECS}

mpi_hello_world: mpi_hello_world.c
	${MPICC} -o mpi_hello_world mpi_hello_world.c

clean:
	rm -f ${EXECS}

**Comment by jjwilke** [comment]
Correct.

But I think LDFLAGS should be:

-L/home/jon/sst-dumpi/lib

-Jeremy

**Comment by jw447** [comment]
The ssh-dumpi folder does not have the lib though. I git clone it from: https://github.com/sstsimulator/sst-dumpi <https://github.com/sstsimulator/sst-dumpi>

**Comment by jjwilke** [comment]
Did you run 'make install'?

**Comment by jw447** [comment]
Should I run “make install” after ‘./bootstrap.sh’? I am not sure since it is not indicated in the instruction.

ThankS,
Jinzhen

**Comment by jjwilke** [comment]
You'll likely want to review the basics of configure scripts, installation to prefix directory, makefiles, etc.  This is not documented in DUMPI since these are standard tools with documentation elsewhere. If there's someone you work with who is familiar with CMake/configure scripts that can help you get started, that would be good.

-Jeremy

**Comment by jw447** [comment]
Okay, I think I can figure that part out. I really appreciate your help.

Thank you very much!
Jinzhen

**Comment by jw447** [comment]
Hi, I think I have another problem.
I followed the exact instruction of using DUMPI from SST Macro 7.1.0. 
```
dumpi > ./ bootstrap .sh
dumpi /build > ../ configure CC= mpicc CXX = mpicxx --enable - libdumpi -- prefix = $DUMPI_PATH
make
make install
```
when I ran the 'make' and 'make install', the error message is:

So please let me know where I did wrong.

Thank you!

[error.txt](https://github.com/sstsimulator/sst-dumpi/files/1351970/error.txt)
